// app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import RootLayout from "./components/RootLayout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="antialiased">
        <RootLayout>{children}</RootLayout>
      </body>
    </html>
  );
}